<?php

/*
	Do not edit this file manually. This copy of global file is overwritten
	by extensions editor.
*/

$installed_extensions = array (
  0 => 
  array (
    'name' => 'English Canadian COA - General',
    'package' => 'chart_en_CA-general',
    'version' => '2.3.0-4',
    'type' => 'chart',
    'active' => false,
    'path' => 'sql',
    'sql' => 'en_CA-general.sql',
  ),
  1 => 
  array (
    'name' => 'Default American coa (5 digits)',
    'package' => 'chart_en_US-general',
    'version' => '2.3.0-3',
    'type' => 'chart',
    'active' => false,
    'path' => 'sql',
    'sql' => 'en_US-general.sql',
  ),
  2 => 
  array (
    'name' => 'Spanish COA - ISO',
    'package' => 'chart_es_ES-general',
    'version' => '2.3.0-5',
    'type' => 'chart',
    'active' => false,
    'path' => 'sql',
    'sql' => 'es_ES-iso.sql',
  ),
);
?>